[project]
site_name="Bluen Documentation"
site_url = "https://axis-engine.github.io/docs"
site_description = "The official documentation for Bluen Engine!"
site_author = "Bluen Engine"

[project.theme]
logo = "images/bluen-standard-dark.svg"
favicon = "images/bluen-standard-dark.svg"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
accent = "blue"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
accent = "light blue"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"